storage:
  media_paths:
    - /Users/tanny/Pictures/facetest
    - /Users/tanny/Documents/texts
    - /Users/tanny/Documents/test_documents
    - /Users/tanny/Documents/Music/Tycho
  thumbnail_path: ./backend/cache/thumbnails

processing:
  batch_size: 32
  workers: 4
  skip_videos: false
